version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_KEY=req_3ZPrqqnZuuNDyPTf7DTcWGGo
      - MINER_POSITIONS_ENDPOINT_URL=https://request.wildsage.io/miner-positions?tier=0
      # metamask
      - HARDCODED_ADDRESS=0xe0a5cfa76Fde7Df6b4159dF6DCC2c309f9b3d5E1,0x1b53aBebFA996203feF4d5EBa3c79E7bf63177B0,0xa3C72bA4183242c892B7A1Ba51D89D94C6C2fdb1
